import type { Metadata } from "next";
import Image from "next/image"
import { Inter } from "next/font/google";
import icon from "../../public/typing-icon.svg"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Image className="logo" src={icon} alt="keyboard logo"></Image>
          <h2>TYPE</h2>
        </header>
        <main>
          {children}
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
